RUN sed -i '1 i echo "!! /etc/bash.nointeractive.bashrc"' /etc/bash.nointeractive.bashrc
RUN sed -i '1 i echo "!! /etc/bash.bashrc - all"' /etc/bash.bashrc
RUN sed -i '10 i echo "!! /etc/bash.bashrc - interactive"' /etc/bash.bashrc
RUN sed -i '1 i echo "!! $HOME bashrc - all"' /etc/skel/.bashrc
RUN sed -i '12 i echo "!! $HOME bashrc - interactive"' /etc/skel/.bashrc
